\newpage

# Databases {#bases-datos}

## Databases Download

After completing the review and validation process, ELSOC databases are made available to the general public. The databases are published and saved in the **Harvard Dataverse** repository in the [COES data folder](https://dataverse.harvard.edu/dataverse/coes_data_repository). This repository allows free and secure access to the databases.

ELSOC is available as cross-sectional databases by wave: waves 2016, 2017, 2018, 2019 and 2021, in R (.RData), SPSS (.sav), Stata 13 (.dta) and Stata 14 (.dta) data formats.

Since 2019, we have published the databases in a longitudinal form to facilitate their use as a panel survey. We share the longitudinal database 2016-2019  in wide format and the longitudinal database 2016-2021 in wide and long structures. We harmonized the variables that have changed over time to allow their longitudinal use.

As part of a continuous improvement process, we might update published databases during the development of ELSOC, due to correction of potential bugs, improvements in data formatting, updating of non-response codes, etc. Therefore, we publish the latest available version in the Harvard Dataverse repository, as well as all previous versions needed.

## Technical Report

This section presents the technical report. See Table \@ref(tab:ficha), which summarizes the main characteristics of ELSOC:

```{r ficha, echo=FALSE, message=FALSE, warning=FALSE}

ficha <- data.frame(caracteristicas = c('Objective', 'Design', 'Instrument', 'Topic features', 'Unit of analysis', 'Target population', 'Sampling frame', 'Sample design', 'Sample unit', 'Frequency', 'Surveying mode', 'Informant', 'Ethic aspects', 'Average duration', 'Representativeness', 'Responsible entity', 'Executing entity'),
                    ELSOC = c('To analyze longitudinally the evolution of conflict and cohesion in Chilean society',
                              'Quantitative study through a structured questionnaire',
                              'The questionnaire is composed of single and multiple closed questions and some open questions. It combines permanent (all waves) and interleaved questions', 
                              'It contains seven thematic modules: Territory, Social networks and attitudes, Citizenship and democracy, Inequality and legitimacy, Social conflict, Health and well-being, and Sociodemographic characterization', 
                              'Individuals',
                              'Men and women between 18 and 75 years old, residents of occupied private households, located in 40 cities (92 communes) of the country',
                              'Sampling frame of blocks of the 2011 pre-census, prepared by the Territorial Intelligence Center (CIT) of the Adolfo Ib치침ez University', 
                              'Probabilistic, stratified, clustered and multistage.',
                              'First cities are selected (UPM), then blocks (USM), sub-blocks and households (UTM). The last selection unit are individuals',
                              'Annually. Refreshment sample in the 3rd year',
                              'Face-to-face survey in the interviewees household. Personal interview applied by an interviewer using a tablet (CAPI system: Computer-assisted personal interviewing)',
                              'Male or female resident in the household, between 18 and 75 years old',
                              'Voluntary interview. Contact information of interviewees is requested, but is not accessible (confidential). Geo-referenced information is also kept confidential. Public access database',
                              '51 minutes',
                              'Approximately 77% of the countrys population and 93% of the urban population in wave 2016',
              'Centre for Social Conflict and Cohesion Studies (COES)',
              'Consultant Stephanie Eckman and Centro de Inteligencia Territorial (CIT) of Adolfo Ib치침ez University (sample design). MicroData Center (CMD) of the University of Chile (collection, data processing and construction of expansion factors)'))
          

ficha %>% 
  kbl(align = rep('l', 2),
      format = table_format,
      booktabs = TRUE,
      longtable = TRUE,
      col.name = c('Characteristics', 'ELSOC'),
      caption = 'ELSOC-COES Technical Report') %>% 
  kable_styling(full_width = FALSE,
                latex_options = c('HOLD_position', 'scale_down', 'repeat_header')) %>%
  column_spec(1, width = "8em") %>% 
  column_spec(2, width = "35em") %>% 

  kable_classic_2() 

```

## Database Usage Protocol

Any publication using ELSOC databases, in any of their versions, must cite the source in the following ways (depending on the database used):

- ELSOC 2016:

**Centre for Social Conflict and Cohesion Studies. (2016). Chilean Longitudinal Social Survey, First Wave (ELSOC_W01_v1.00). [Database]. Santiago, Chile: Centre for Social Conflict and Cohesion Studies (COES). www.coes.cl**

- ELSOC 2017:

**Centre for Social Conflict and Cohesion Studies.  (2017). Chilean Longitudinal Social Survey, Second Wave (ELSOC_W02_v1.00). [Database]. Santiago, Chile: Centre for Social Conflict and Cohesion Studies (COES). www.coes.cl**

- ELSOC 2018:

**Centre for Social Conflict and Cohesion Studies.  (2018). Chilean Longitudinal Social Survey, Third Wave (ELSOC_W03_v1.00). [Database]. Santiago, Chile: Centre for Social Conflict and Cohesion Studies (COES). www.coes.cl**

- ELSOC 2019:

**Centre for Social Conflict and Cohesion Studies. (2019). Chilean Longitudinal Social Survey, Fourth Wave (ELSOC_W04_v1.00). [Database]. Santiago, Chile: Centre for Social Conflict and Cohesion Studies (COES). www.coes.cl**

- ELSOC 2021:

**Centre for Social Conflict and Cohesion Studies. (2021). Chilean Longitudinal Social Survey, Fifth Wave (ELSOC_W05_v1.00). [Database]. Santiago, Chile: Centre for Social Conflict and Cohesion Studies (COES). www.coes.cl**

Or in its longitudinal format:

**Centre for Social Conflict and Cohesion Studies. (2021). Chilean Longitudinal Social Survey, Combined Panel Version 2016-2019 (ELSOC_Wide_2016_2019_v1.00). [Database]. Santiago, Chile: Centre for Social Conflict and Cohesion Studies (COES). www.coes.cl**

Finally, if you wish to cite this User's Manual:

**Centre for Social Conflict and Cohesion Studies. (2021). Chilean Longitudinal Social Survey User's Manual. Santiago, Chile: Centre for Social Conflict and Cohesion Studies (COES).**

